version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todo-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: todoDB
    ports:
      - "5433:5432"   

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
